export const MESSAGE_PING = 'MESSAGE_PING';
export const MESSAGE_PONG = 'MESSAGE_PONG';

export const MESSAGE_CHAT = 'MESSAGE_CHAT';
export const MESSAGE_CHAT_UPDATED = 'MESSAGE_CHAT_UPDATED';

export const MESSAGE_SIGN_IN = 'MESSAGE_SIGN_IN';
export const MESSAGE_SIGN_IN_RESPONSE = 'MESSAGE_SIGN_IN_RESPONSE';
export const MESSAGE_GAME_START = 'MESSAGE_GAME_START';
export const MESSAGE_GAME_STOP = 'MESSAGE_GAME_STOP';
export const MESSAGE_GAME_RESET = 'MESSAGE_GAME_RESET';
export const MESSAGE_KEY_PRESSED = 'MESSAGE_KEY_PRESSED';
export const MESSAGE_KEY_RELEASED = 'MESSAGE_KEY_RELEASED';
export const MESSAGE_PLAYER_LEFT = 'MESSAGE_PLAYER_LEFT';
export const MESSAGE_STATE_UPDATED = 'MESSAGE_STATE_UPDATED';
export const MESSAGE_FRUIT_GENERATED = 'MESSAGE_FRUIT_GENERATED';
export const MESSAGE_FRUIT_EATEN = 'MESSAGE_FRUIT_EATEN';
