export const MESSAGE_PING = 'MESSAGE_PING';
export const MESSAGE_PONG = 'MESSAGE_PONG';

export const MESSAGE_SIGN_IN = 'MESSAGE_SIGN_IN';
export const MESSAGE_SIGN_IN_RESPONSE = 'MESSAGE_SIGN_IN_RESPONSE';
/* export const MESSAGE_GAME_START = 'MESSAGE_GAME_START';
export const MESSAGE_GAME_END = 'MESSAGE_GAME_END';*/
export const MESSAGE_KEY_PRESSED = 'MESSAGE_KEY_PRESSED';
export const MESSAGE_KEY_RELEASED = 'MESSAGE_KEY_RELEASED';
export const MESSAGE_STATE_UPDATED = 'MESSAGE_STATE_UPDATED';
